version: '3'
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - AWS_ACCESS_KEY=YOUR_AWS_ACCESS_KEY
      - AWS_SECRET_KEY=YOUR_AWS_SECRET_KEY
      - AWS_REGION=eu-central-1
      - DYNAMODB_TABLE_NAME=recorded-audio
      - S3_BUCKET_NAME=recorded-audio-files
      - USERNAME=admin
      - PASSWORD=password
      - JWT_TOKEN_SECRET=changeMeToYourSecretWords
  frontend:
    stdin_open: true
    environment:
      - AWS_ACCESS_KEY=YOUR_AWS_ACCESS_KEY
      - AWS_SECRET_KEY=YOUR_AWS_SECRET_KEY
      - AWS_REGION=eu-central-1
      - DYNAMODB_TABLE_NAME=recorded-audio
      - REACT_APP_BUCKET_NAME=recorded-audio-files
    build:
      dockerfile: Dockerfile
      context: ./frontend
